# Generated by Django 3.0.5 on 2021-03-12 12:51

from django.db import migrations, models
import lib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(default=lib.utils.gen_uuid, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('storyline', models.CharField(max_length=550)),
                ('genre', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('runtime', models.IntegerField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
